function edittingASFplot(xaxi,yaxi,colorbarlim,x_lab,y_lab,x_tick,y_tick,colorbar_lab,c_units,axi_units,gridon,lineon,boxon,boxcolor)
opengl software
if lineon
    % 4 lines
line('XData', [300 475], 'YData', [140 140], 'LineStyle', '-', ...
    'LineWidth', 1, 'Color','y');
line('XData', [300 475], 'YData', [55 55], 'LineStyle', '-', ...
    'LineWidth', 1, 'Color','y');
line('XData', [300 300], 'YData', [55 140], 'LineStyle', '-', ...
    'LineWidth', 1, 'Color','y');
line('XData', [475 475], 'YData', [55 140], 'LineStyle', '-', ...
   'LineWidth', 1, 'Color','y');

line('XData', [170 250], 'YData', [310 310], 'LineStyle', '-', ...
    'LineWidth', 1, 'Color','r');
line('XData', [170 250], 'YData', [225 225], 'LineStyle', '-', ...
    'LineWidth', 1, 'Color','r');
line('XData', [170 170], 'YData', [225 310], 'LineStyle', '-', ...
    'LineWidth', 1, 'Color','r');
line('XData', [250 250], 'YData', [225 310], 'LineStyle', '-', ...
    'LineWidth', 1, 'Color','r');

line('XData', [340 470], 'YData', [175 175], 'LineStyle', '-', ...
   'LineWidth', 1, 'Color','m');
line('XData', [340 470], 'YData', [280 280], 'LineStyle', '-', ...
   'LineWidth', 1, 'Color','m');
line('XData', [340 340], 'YData', [175 280], 'LineStyle', '-', ...
   'LineWidth', 1, 'Color','m');
line('XData', [470 470], 'YData', [175 280], 'LineStyle', '-', ...
   'LineWidth', 1, 'Color','m');
%end
%big line
% line('XData', [300 440], 'YData', [170 170], 'LineStyle', '-', ...
%     'LineWidth', 1, 'Color','m');
% line('XData', [300 440], 'YData', [310 310], 'LineStyle', '-', ...
%     'LineWidth', 1, 'Color','m');
% line('XData', [300 300], 'YData', [170 310], 'LineStyle', '-', ...
%     'LineWidth', 1, 'Color','m');
% line('XData', [440 440], 'YData', [170 310], 'LineStyle', '-', ...
%     'LineWidth', 1, 'Color','m');
end
 grey=[0.7,0.7,0.7];
 
 xlim(xaxi);ylim(yaxi);
 if y_tick==0
 set(gca,'Clim',colorbarlim,...
     'XTickLabel',x_lab,'YTickLabel',y_lab,...
     'FontSize',15);
 else
 set(gca,'Clim',colorbarlim,...
     'xtick',x_tick,'ytick',y_tick,'XTickLabel',x_lab,'YTickLabel',y_lab,...
     'FontSize',15);
 end
 %set(gca,'Clim',colorbarlim,'FontSize',15);
 xlabh = xlabel(axi_units);
 ylabh = ylabel(axi_units);
 %xlabh = xlabel(axi_units);
 set(xlabh,'FontSize',15);
 set(ylabh,'FontSize',15);
 h = colorbar;
 %set(h,'XTickLabel',colorbar_lab,'FontSize',15);
 set(h,'FontSize',15);
 ylabel(h,c_units);
 clabh=ylabel(h,c_units);
 set(clabh,'FontSize',15,'FontWeight','bold');
 box off;
 
 if gridon
  grid on;
  hAx1 = gca;
  %axes('Color','none');
  %hAx1 = axes('Parent',figure,'Color','none');
  % hold(hAx1,'all');
  hAx2 = axes('Position',get(hAx1,'Position'), ...
    'Color','none', ...
    'XGrid','on', 'YGrid','on', ...
    'Box','off', 'XColor',grey, 'YColor',grey, ...
    'XTickLabel',[], 'YTickLabel',[], ...
    'XTick',get(hAx1,'XTick'), 'YTick',get(hAx1,'YTick'), ...
    'XLim',get(hAx1,'XLim'), 'YLim',get(hAx1,'YLim'),...
    'YDir','Reverse');%somehow the y direction of grid has been reversed
    axis tight;
    %# link the two axes to share the same limits on pan/zoom
   % linkaxes([hAx1 hAx2],'xy');
 end 
 if boxon
     hAx3 = axes('Position',get(hAx2,'Position'), ...
    'Color','none', ...
    'XGrid','off', 'YGrid','off', ...
    'Box','on', 'XColor',boxcolor, 'YColor',boxcolor,'LineWidth',1.5, ...
    'XTickLabel',[], 'YTickLabel',[], ...
    'XTick',[], 'YTick',[], ...
    'XLim',get(hAx2,'XLim'), 'YLim',get(hAx2,'YLim'));
    %# link the two axes to share the same limits on pan/zoom
    linkaxes([hAx2 hAx3],'xy');
    axis tight;
 end
 colormap jet
 end